In [2]:
import matplotlib.pyplot as plt

import numpy as np
import time
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import numpy

np.set_printoptions(suppress=True)
%matplotlib inline

from sklearn.preprocessing import MinMaxScaler
from pylab import *
mpl.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False 
import seaborn as sns 
sns.set_palette("husl") #设置所有图的颜色，使用hls色彩空间
import numpy as np
from sklearn.metrics import f1_score #均方误差
from sklearn.metrics import classification_report #平方绝对误差

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

In [3]:
#读取 cleandata附件1.csv
data1=pd.read_csv('cleandata附件1.csv',encoding='gbk')
data1.head()

,企业代号,企业名称,是否违约,"('金额', 'count')_x","('金额', 'mean')_x","('金额', 'std')_x","('金额', 'min')_x","('金额', '25%')_x","('金额', '50%')_x","('金额', '75%')_x",...,"('价税合计', 'std')","('价税合计', 'min')","('价税合计', '25%')","('价税合计', '50%')","('价税合计', '75%')","('价税合计', 'max')","('发票状态', 'count')","('发票状态', 'unique')","('发票状态', 'top')","('发票状态', 'freq')"
0,E1,***电器销售有限公司,否,3441.0,1.733225e+06,3.917948e+06,-9823008.85,265.4900,970.870,98201.77,...,493962.263666,-1145690.00,122176.500,600256.75,1096494.00,1169977.00,8110,2,有效发票,7886
1,E2,***技术有限责任公司,否,32156.0,5.117059e+03,2.511614e+04,-99857.14,172.4200,297.345,766.99,...,46052.957199,-100000.00,9012.000,60000.00,100000.00,100000.00,12707,2,有效发票,11665
2,E3,***电子(中国)有限公司***分公司,否,4561.0,1.210060e+04,5.457243e+04,-321045.22,211.6500,367.930,1655.66,...,120731.750911,-1127351.73,1680.000,3907.00,22569.62,1160953.50,24073,2,有效发票,23688
3,E4,***发展有限责任公司,否,558.0,5.881122e+05,2.001187e+06,-3798756.81,319.1175,938.690,33980.58,...,271272.684844,-1169732.68,1125048.355,1151000.00,1166400.00,1169980.44,2231,2,有效发票,2041
4,E5,***供应链管理有限公司,否,2169.0,9.310316e+04,3.316620e+05,-98909.09,389.3800,80653.210,99115.04,...,314360.510764,-115000.00,112100.000,115430.00,115913.00,1159532.60,1060,2,有效发票,1005

In [4]:
#读取 cleandata附件2.csv
data2=pd.read_csv('cleandata附件2.csv',encoding='gbk')
data2.head()

,企业代号,企业名称,"('金额', 'count')_x","('金额', 'mean')_x","('金额', 'std')_x","('金额', 'min')_x","('金额', '25%')_x","('金额', '50%')_x","('金额', '75%')_x","('金额', 'max')_x",...,"('价税合计', 'std')","('价税合计', 'min')","('价税合计', '25%')","('价税合计', '50%')","('价税合计', '75%')","('价税合计', 'max')","('发票状态', 'count')","('发票状态', 'unique')","('发票状态', 'top')","('发票状态', 'freq')"
0,E124,个体经营E124,17411.0,52971.025771,124108.978850,-881892.24,530.970,9999.03,90909.0900,5504587.16,...,415753.233732,-1000000.0,527509.96,1000000.00,1000000.000,1109999.99,1293,2,有效发票,1099
1,E125,个体经营E125,20288.0,54017.359583,122409.037582,-970873.79,640.150,13643.74,91743.1200,5504587.16,...,400992.461740,-1000000.0,519571.52,1000000.00,1000000.000,1109999.99,1595,2,有效发票,1380
2,E126,个体经营E126,533.0,220126.048780,300449.260954,-95774.37,6767.000,86150.86,293473.1800,999961.31,...,408119.411951,-1016304.0,71162.00,322403.13,881583.225,1082430.50,1516,2,有效发票,1264
3,E127,个体经营E127,1450.0,1194.927276,9323.027176,-513.27,172.745,286.74,549.2025,283018.87,...,249002.208519,-900000.0,100000.00,102900.00,102999.000,1029999.99,4026,2,有效发票,3904
4,E128,个体经营E128,3222.0,3197.470261,15130.191636,-92307.69,158.245,283.02,770.6050,359223.30,...,292912.269757,0.0,99500.00,99990.00,100000.000,1000000.00,1255,2,有效发票,1161

In [5]:
data1.columns

Index(['企业代号', '企业名称', '是否违约', '('金额', 'count')_x', '('金额', 'mean')_x',
       '('金额', 'std')_x', '('金额', 'min')_x', '('金额', '25%')_x',
       '('金额', '50%')_x', '('金额', '75%')_x', '('金额', 'max')_x',
       '('税额', 'count')_x', '('税额', 'mean')_x', '('税额', 'std')_x',
       '('税额', 'min')_x', '('税额', '25%')_x', '('税额', '50%')_x',
       '('税额', '75%')_x', '('税额', 'max')_x', '('价税合计', 'count')_x',
       '('价税合计', 'mean')_x', '('价税合计', 'std')_x', '('价税合计', 'min')_x',
       '('价税合计', '25%')_x', '('价税合计', '50%')_x', '('价税合计', '75%')_x',
       '('价税合计', 'max')_x', '('发票状态', 'count')_x', '('发票状态', 'unique')_x',
       '('发票状态', 'top')_x', '('发票状态', 'freq')_x', '('金额', 'count')',
       '('金额', 'mean')', '('金额', 'std')', '('金额', 'min')', '('金额', '25%')',
       '('金额', '50%')', '('金额', '75%')', '('金额', 'max')', '('税额', 'count')',
       '('税额', 'mean')', '('税额', 'std')', '('税额', 'min')', '('税额', '25%')',
       '('税额', '50%')', '('税额', '75%')', '('税额', 'max')', '('价税合计', 'count')',
       '('价税合计', 'mean')', '('价税合计', 'std')', '('价税合计', 'min')',
       '('价税合计', '25%')', '('价税合计', '50%')', '('价税合计', '75%')',
       '('价税合计', 'max')', '('发票状态', 'count')', '('发票状态', 'unique')',
       '('发票状态', 'top')', '('发票状态', 'freq')'],
      dtype='object')

In [6]:
data2.columns

Index(['企业代号', '企业名称', '('金额', 'count')_x', '('金额', 'mean')_x',
       '('金额', 'std')_x', '('金额', 'min')_x', '('金额', '25%')_x',
       '('金额', '50%')_x', '('金额', '75%')_x', '('金额', 'max')_x',
       '('税额', 'count')_x', '('税额', 'mean')_x', '('税额', 'std')_x',
       '('税额', 'min')_x', '('税额', '25%')_x', '('税额', '50%')_x',
       '('税额', '75%')_x', '('税额', 'max')_x', '('价税合计', 'count')_x',
       '('价税合计', 'mean')_x', '('价税合计', 'std')_x', '('价税合计', 'min')_x',
       '('价税合计', '25%')_x', '('价税合计', '50%')_x', '('价税合计', '75%')_x',
       '('价税合计', 'max')_x', '('发票状态', 'count')_x', '('发票状态', 'unique')_x',
       '('发票状态', 'top')_x', '('发票状态', 'freq')_x', '('金额', 'count')',
       '('金额', 'mean')', '('金额', 'std')', '('金额', 'min')', '('金额', '25%')',
       '('金额', '50%')', '('金额', '75%')', '('金额', 'max')', '('税额', 'count')',
       '('税额', 'mean')', '('税额', 'std')', '('税额', 'min')', '('税额', '25%')',
       '('税额', '50%')', '('税额', '75%')', '('税额', 'max')', '('价税合计', 'count')',
       '('价税合计', 'mean')', '('价税合计', 'std')', '('价税合计', 'min')',
       '('价税合计', '25%')', '('价税合计', '50%')', '('价税合计', '75%')',
       '('价税合计', 'max')', '('发票状态', 'count')', '('发票状态', 'unique')',
       '('发票状态', 'top')', '('发票状态', 'freq')'],
      dtype='object')

In [7]:
data=pd.concat([data1,data2])
data.shape

(425, 59)

In [8]:
data.isnull().sum()

企业代号                      0
企业名称                      0
是否违约                    302
('金额', 'count')_x         0
('金额', 'mean')_x          0
('金额', 'std')_x           2
('金额', 'min')_x           0
('金额', '25%')_x           0
('金额', '50%')_x           0
('金额', '75%')_x           0
('金额', 'max')_x           0
('税额', 'count')_x         0
('税额', 'mean')_x          0
('税额', 'std')_x           2
('税额', 'min')_x           0
('税额', '25%')_x           0
('税额', '50%')_x           0
('税额', '75%')_x           0
('税额', 'max')_x           0
('价税合计', 'count')_x       0
('价税合计', 'mean')_x        0
('价税合计', 'std')_x         2
('价税合计', 'min')_x         0
('价税合计', '25%')_x         0
('价税合计', '50%')_x         0
('价税合计', '75%')_x         0
('价税合计', 'max')_x         0
('发票状态', 'count')_x       0
('发票状态', 'unique')_x      0
('发票状态', 'top')_x         0
('发票状态', 'freq')_x        0
('金额', 'count')           0
('金额', 'mean')            0
('金额', 'std')             0
('金额', 'min')             0
('金额', '25%')             0
('金额', '50%')             0
('金额', '75%')             0
('金额', 'max')             0
('税额', 'count')           0
('税额', 'mean')            0
('税额', 'std')             0
('税额', 'min')             0
('税额', '25%')             0
('税额', '50%')             0
('税额', '75%')             0
('税额', 'max')             0
('价税合计', 'count')         0
('价税合计', 'mean')          0
('价税合计', 'std')           0
('价税合计', 'min')           0
('价税合计', '25%')           0
('价税合计', '50%')           0
('价税合计', '75%')           0
('价税合计', 'max')           0
('发票状态', 'count')         0
('发票状态', 'unique')        0
('发票状态', 'top')           0
('发票状态', 'freq')          0
dtype: int64

In [9]:
data["('金额', 'std')_x"].fillna(data["('金额', 'std')_x"].mean(),inplace=True)
data["('税额', 'std')_x"].fillna(data["('税额', 'std')_x"].mean(),inplace=True)
data["('价税合计', 'std')_x"].fillna(data["('价税合计', 'std')_x"].mean(),inplace=True)

In [10]:
data.isnull().sum()

企业代号                      0
企业名称                      0
是否违约                    302
('金额', 'count')_x         0
('金额', 'mean')_x          0
('金额', 'std')_x           0
('金额', 'min')_x           0
('金额', '25%')_x           0
('金额', '50%')_x           0
('金额', '75%')_x           0
('金额', 'max')_x           0
('税额', 'count')_x         0
('税额', 'mean')_x          0
('税额', 'std')_x           0
('税额', 'min')_x           0
('税额', '25%')_x           0
('税额', '50%')_x           0
('税额', '75%')_x           0
('税额', 'max')_x           0
('价税合计', 'count')_x       0
('价税合计', 'mean')_x        0
('价税合计', 'std')_x         0
('价税合计', 'min')_x         0
('价税合计', '25%')_x         0
('价税合计', '50%')_x         0
('价税合计', '75%')_x         0
('价税合计', 'max')_x         0
('发票状态', 'count')_x       0
('发票状态', 'unique')_x      0
('发票状态', 'top')_x         0
('发票状态', 'freq')_x        0
('金额', 'count')           0
('金额', 'mean')            0
('金额', 'std')             0
('金额', 'min')             0
('金额', '25%')             0
('金额', '50%')             0
('金额', '75%')             0
('金额', 'max')             0
('税额', 'count')           0
('税额', 'mean')            0
('税额', 'std')             0
('税额', 'min')             0
('税额', '25%')             0
('税额', '50%')             0
('税额', '75%')             0
('税额', 'max')             0
('价税合计', 'count')         0
('价税合计', 'mean')          0
('价税合计', 'std')           0
('价税合计', 'min')           0
('价税合计', '25%')           0
('价税合计', '50%')           0
('价税合计', '75%')           0
('价税合计', 'max')           0
('发票状态', 'count')         0
('发票状态', 'unique')        0
('发票状态', 'top')           0
('发票状态', 'freq')          0
dtype: int64

In [11]:
data['是否违约']=data['是否违约'].map({'是':1,"否":0})
data["('发票状态', 'top')"]=data["('发票状态', 'top')"].map({'有效发票':1,"作废发票":0})
del data["('发票状态', 'top')_x"]

In [12]:
train_X=data[data['是否违约'].isnull()==False][data.columns[3:]]
train_Y=data[data['是否违约'].isnull()==False]['是否违约']
pred_X=data[data['是否违约'].isnull()==True][data.columns[3:]]

In [13]:
from collections import Counter
Counter(train_Y)

Counter({0.0: 96, 1.0: 27})

In [14]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE().fit_resample(train_X, train_Y)
print(sorted(Counter(y_resampled).items()))

ModuleNotFoundError: No module named 'imblearn'

In [15]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y = train_test_split(X_resampled,y_resampled,test_size=0.3,random_state=5)

NameError: name 'X_resampled' is not defined

In [72]:
model = RandomForestClassifier()
model.fit(train_X,train_y)

print(classification_report(test_y, model.predict(test_X)))

              precision    recall  f1-score   support

         0.0       0.91      0.97      0.94        32
         1.0       0.96      0.88      0.92        26

    accuracy                           0.93        58
   macro avg       0.94      0.93      0.93        58
weighted avg       0.93      0.93      0.93        58

In [73]:
model = AdaBoostClassifier()
model.fit(train_X,train_y)

print(classification_report(test_y, model.predict(test_X)))

              precision    recall  f1-score   support

         0.0       0.90      0.81      0.85        32
         1.0       0.79      0.88      0.84        26

    accuracy                           0.84        58
   macro avg       0.84      0.85      0.84        58
weighted avg       0.85      0.84      0.85        58

In [74]:
model = SVC()
model.fit(train_X,train_y)

print(classification_report(test_y, model.predict(test_X)))

              precision    recall  f1-score   support

         0.0       0.90      0.59      0.72        32
         1.0       0.65      0.92      0.76        26

    accuracy                           0.74        58
   macro avg       0.78      0.76      0.74        58
weighted avg       0.79      0.74      0.74        58

In [1]:
from xgboost.sklearn import XGBClassifier

model = XGBClassifier()
model.fit(train_X,train_y)

print(classification_report(test_y, model.predict(test_X)))

NameError: name 'train_X' is not defined